name: Android CI
on: [push,pull_request]

env:
  REPO_URL: https://github.com/kkevsekk1/AutoX
  REPO_BRANCH: dev
#  FEEDS_CONF: feeds.conf.default
#  CONFIG_FILE: .config
#  DIY_P1_SH: diy-part1.sh
#  DIY_P2_SH: diy-part2.sh
#  SSH_ACTIONS: false
#  UPLOAD_BIN_DIR: false
#  UPLOAD_FIRMWARE: false
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_ARTIFACT: false
  SSH_ACTIONS: false
#  KERNEL_TEST: true
  FILETARNAME: autox.tar.gz
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        #sed -i 's#maven.*http://120.25.164.*##g' ./build.gradle
        sed -i 's#File propFile =new File.*#File propFile =rootProject.file("keystore.properties")#g' ./inrt/build.gradle
        sed -i 's#File propFile =new File.*#File propFile =rootProject.file("keystore.properties")#g' ./app/build.gradle
        chmod 777 ./gradlew && ./gradlew :inrt:assemble &&  ./gradlew inrt:cp2APP && ./gradlew :app:assembleRelease
        tar -czf $FILETARNAME app/build/outputs
        
    - name: Upload firmware to cowtransfer
      if: env.UPLOAD_COWTRANSFER == 'true' || contains(github.event.action, 'ssh')
      run: |
        ls -l
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress $FILETARNAME 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
    - name: Upload firmware to WeTransfer
      if: env.UPLOAD_WETRANSFER == 'true' || contains(github.event.action, 'ssh')
      run: |
        ls -l
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress $FILETARNAME 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"


